In [6]:
import numpy as np

In [7]:
x = np.array([1,2,3])

y = np.array([4,5,6])

print(x + y)

[5 7 9]


In [9]:
xx = np.array([[1,2,3]])

yy = np.array([[4,5,6]])

print(xx + yy)

[[5 7 9]]


In [12]:
x.ndim

1

In [14]:
xx.ndim

2

In [16]:
x.dtype

dtype('int64')

In [18]:
x.fun

AttributeError: 'numpy.ndarray' object has no attribute 'fun'

In [20]:
np.array?

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if ``__array__`` returns a copy, if obj is a nested
    sequence, or if a copy is needed to satisfy any of the other
    requirements (``dtype``, ``order``, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly crea

In [22]:
x.shape

(3,)

In [24]:
xx.shape

(1, 3)

In [26]:
y.sum()

15

In [8]:
x = np.array([1,2,3,4,5,6])
print('beginning x:\n', x)
x_reshape = x.reshape((2, 3)) 
print('reshaped x:\n', x_reshape)

re_x = x_reshape.reshape([-1,])
print("Back to one dimension", re_x)

beginning x:
 [1 2 3 4 5 6]
reshaped x:
 [[1 2 3]
 [4 5 6]]
Back to one dimension [1 2 3 4 5 6]


In [36]:
x.sum?

Docstring:
a.sum(axis=None, dtype=None, out=None, keepdims=False, initial=0, where=True)

Return the sum of the array elements over the given axis.

Refer to `numpy.sum` for full documentation.

See Also
--------
numpy.sum : equivalent function
Type:      builtin_function_or_method

In [10]:
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [12]:
x ** 2

array([ 1,  4,  9, 16, 25, 36])

In [14]:
np.random.normal?

Docstring:
normal(loc=0.0, scale=1.0, size=None)

Draw random samples from a normal (Gaussian) distribution.

The probability density function of the normal distribution, first
derived by De Moivre and 200 years later by both Gauss and Laplace
independently [2]_, is often called the bell curve because of
its characteristic shape (see the example below).

The normal distributions occurs often in nature.  For example, it
describes the commonly occurring distribution of samples influenced
by a large number of tiny, random disturbances, each with its own
unique distribution [2]_.

.. note::
    New code should use the `~numpy.random.Generator.normal`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
loc : float or array_like of floats
    Mean ("centre") of the distribution.
scale : float or array_like of floats
    Standard deviation (spread or "width") of the distribution. Must be
    non-negative.
size : int 

In [16]:
rand = np.random.normal(size=50)
rand

array([-0.33595634, -1.04710942,  0.68274178, -0.7966354 , -0.17813175,
        1.24981109, -0.30213259,  1.03658323, -1.33245549, -0.79357092,
       -1.11361627,  0.45424017,  0.65514923, -0.94014348,  0.71638461,
        0.91012866, -1.00315191, -0.34178039, -0.63783886, -0.4036607 ,
        0.01230157, -1.1999954 , -0.46161406, -0.26077402, -0.23041416,
        1.03645327, -0.5852009 , -0.40019371, -0.90038173, -1.5209668 ,
       -0.10916715, -0.44681632,  0.19991195, -1.92146738, -0.60709493,
        0.41155191,  0.220723  , -2.25541528, -1.13734643, -0.86521582,
       -0.52993974, -1.73858305, -2.35346005,  1.19266252, -0.962557  ,
       -0.56395346, -0.14906187, -2.29859182,  0.56462369,  0.5409975 ])

In [20]:
rand = np.random.normal(size=50)
rand

array([ 1.85633426,  0.27029613,  1.29179937,  0.40907396, -1.87828084,
       -0.0060003 ,  0.01658343, -0.84120637,  0.31893058, -0.5055761 ,
        0.89337235,  0.08354106,  0.7761576 , -2.83577546,  0.74937957,
        0.54105885,  2.14959684, -2.35154555, -0.24779966, -0.34977082,
        1.96010969, -0.30546564,  1.26823486, -0.46686212, -0.45971083,
        0.73322558, -0.8002378 ,  0.12153177,  1.51267685, -0.10666248,
        1.89928842, -1.12241261,  2.53936057,  0.98346215, -0.91458555,
        0.04416434, -0.59414888, -0.87322558,  1.16407479,  0.3960747 ,
       -0.46196537,  0.52779228,  0.11038006,  0.53395692,  0.73311013,
       -0.92687377,  0.26130962,  1.04748747,  1.05539185,  1.80093214])

In [30]:
y = rand + np.random.normal(loc=50, scale=1, size=50)

In [32]:
np.corrcoef?

Signature:      
np.corrcoef(
    x,
    y=None,
    rowvar=True,
    bias=<no value>,
    ddof=<no value>,
    *,
    dtype=None,
)
Call signature:  np.corrcoef(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function corrcoef at 0x106f8db20>
File:            /opt/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py
Docstring:      
Return Pearson product-moment correlation coefficients.

Please refer to the documentation for `cov` for more detail.  The
relationship between the correlation coefficient matrix, `R`, and the
covariance matrix, `C`, is

.. math:: R_{ij} = \frac{ C_{ij} } { \sqrt{ C_{ii} C_{jj} } }

The values of `R` are between -1 and 1, inclusive.

Parameters
----------
x : array_like
    A 1-D or 2-D array containing multiple variables and observations.
    Each row of `x` represents a variable, and each column a single
    observation of all those variables. Also see `rowvar` below.
y : array_like, optional
    An additional se

In [34]:
np.corrcoef(rand, y)

array([[1.        , 0.69714076],
       [0.69714076, 1.        ]])

In [38]:
print(np.random.normal(scale=5, size=2))
print(np.random.normal(scale=5, size=2))

[5.20368612 3.40671324]
[ 6.68026239 12.18599498]


In [46]:
rng1 = np.random.default_rng(1303)
print(rng1.normal(scale=5, size=2))
rng2 = np.random.default_rng(1303)
print(rng2.normal(scale=5, size=2))

[ 4.09482632 -1.07485605]
[ 4.09482632 -1.07485605]


In [48]:
rng = np.random.default_rng(3)
y = rng.standard_normal(10)
np.mean(y), y.mean()

(-0.1126795190952861, -0.1126795190952861)

In [50]:
np.var(y), y.var(), np.mean((y - y.mean()) ** 2)

(2.7243406406465125, 2.7243406406465125, 2.7243406406465125)

In [52]:
X = rng.standard_normal((10, 3))
X

array([[ 0.22578661, -0.35263079, -0.28128742],
       [-0.66804635, -1.05515055, -0.39080098],
       [ 0.48194539, -0.23855361,  0.9577587 ],
       [-0.19980213,  0.02425957,  1.54582085],
       [ 0.54510552, -0.50522874, -0.18283897],
       [ 0.54052513,  1.93508803, -0.26962033],
       [-0.24355868,  1.0023136 , -0.88645994],
       [-0.29172023,  0.88253897,  0.58035002],
       [ 0.0915167 ,  0.67010435, -2.82816231],
       [ 1.02130682, -0.95964476, -1.66861984]])

In [54]:
X.shape

(10, 3)

In [56]:
X.mean(axis=0)

array([ 0.15030588,  0.14030961, -0.34238602])

In [61]:
x = rng.standard_normal(100)
x

array([-0.93058888,  0.48127449,  2.46313203, -0.24613355, -0.55586578,
       -1.17115683, -1.33501096,  0.52498323,  0.85080303,  0.00917472,
        0.33257599,  0.11591658,  0.13865485, -1.52615905, -0.45811827,
        0.11147931, -0.78316678, -0.47642974, -0.81912018, -0.33349667,
        0.85310827, -0.40658035, -0.15387068,  0.81371836,  0.64477021,
        1.69520756, -2.09048508,  0.85685894, -0.48228409,  0.13469182,
        0.83771938,  1.08325316,  1.03935069,  0.15510669,  1.60966268,
       -0.28297423, -0.14098191,  0.79935119, -0.55137241,  2.16090626,
        1.01920657,  2.17557532, -0.02658919, -0.38308855,  0.167048  ,
        0.7345765 , -0.58742769,  0.37970175, -0.01680428,  1.61568176,
       -0.66270181,  1.04616177, -0.64386354, -0.96063419, -0.71029943,
       -1.19018586,  0.14635036,  1.0312608 ,  0.16431488,  0.62432511,
        1.6321742 ,  0.27002645,  0.19516236, -0.27506147, -1.60824229,
        0.75973893, -1.75646045,  0.65267644, -0.01432034,  1.12